### ISSUE TITLE
Common errors plz help!

### ISSUE THREAD

**Issue by FelipeSulser** [FelipeSulser/Scala_DataStructures#3]
I always have these errors and I have no idea what I'm doing wrong, please copy my heap and try to compile it.

1) Whenever I need an Int and I put a 1 or any number it says : `type mismatch; found : scala.Int(1) required: Int`

2) When I compare two Ints with "<" or ">" it says that "<" or ">" is not a member of type parameter Int

WHY? :(

**Comment by HaritzPuerto** [comment]
I'm not sure, but why do you write [Int]? [A] is for writing generic types, if you want a heap of integers, just make it but don't write a generic type [Int] because you don't need it. 
Actually, I think [Int] is overwriting the type Int, and as it is not a subtype or Ordered (you have to write A <% Ordered[A]), you cannot compare it.

**Comment by FelipeSulser** [comment]
hmm i see, i just wrote Int to make it initially only an "Int" heap and then make it general
